# Generated by Django 4.1.7 on 2023-03-27 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interprete', models.CharField(max_length=100)),
                ('clase', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=100)),
                ('detalle', models.TextField(max_length=1000)),
                ('descripcion', models.TextField(max_length=1000)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='interprete')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
